# Generated by Django 5.0 on 2024-10-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
